{% set name = "robocorp-truststore" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/robocorp_truststore-{{ version }}.tar.gz
  sha256: 92d8f3d6dc10b9b7825683ae8dc1e134a0c3ade81c99554e3ddd4eafa59a8acf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.10

test:
  imports:
    - truststore
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Verify certificates using native system trust stores
  home: https://github.com/robocorp/truststore
  dev_url: https://github.com/robocorp/truststore
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - osrjv
